import type { Metadata } from "next";
import { Inter, Karantina } from "next/font/google";
import "./globals.css";
import ApolloClientProvider from "@/components/providers/apollo-provider";
import Header from "@/components/navigation/header";
import localFont from "next/font/local";
import Footer from "@/components/navigation/footer";

const helveticaNeue = localFont({
  src: [
    {
      path: "../../public/fonts/helvetica-neue-5/HelveticaNeueUltraLightItalic.otf",
      weight: "100",
      style: "italic",
    },
    {
      path: "../../public/fonts/helvetica-neue-5/HelveticaNeueUltraLight.otf",
      weight: "100",
      style: "normal",
    },
    {
      path: "../../public/fonts/helvetica-neue-5/HelveticaNeueLightItalic.otf",
      weight: "200",
      style: "italic",
    },
    {
      path: "../../public/fonts/helvetica-neue-5/HelveticaNeueLight.otf",
      weight: "200",
      style: "normal",
    },
    {
      path: "../../public/fonts/helvetica-neue-5/HelveticaNeueThinItalic.otf",
      weight: "300",
      style: "italic",
    },
    {
      path: "../../public/fonts/helvetica-neue-5/HelveticaNeueThin.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/helvetica-neue-5/HelveticaNeueRoman.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/helvetica-neue-5/HelveticaNeueItalic.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../../public/fonts/helvetica-neue-5/HelveticaNeueMediumItalic.otf",
      weight: "500",
      style: "italic",
    },
    {
      path: "../../public/fonts/helvetica-neue-5/HelveticaNeueMedium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/helvetica-neue-5/HelveticaNeueHeavyItalic.otf",
      weight: "600",
      style: "italic",
    },
    {
      path: "../../public/fonts/helvetica-neue-5/HelveticaNeueHeavy.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/helvetica-neue-5/HelveticaNeueBoldItalic.otf",
      weight: "700",
      style: "italic",
    },
    {
      path: "../../public/fonts/helvetica-neue-5/HelveticaNeueBold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/helvetica-neue-5/HelveticaNeueBlackItalic.otf",
      weight: "800",
      style: "italic",
    },
    {
      path: "../../public/fonts/helvetica-neue-5/HelveticaNeueBlack.otf",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-helvetica-neue",
  display: "swap",
});

const karantina = Karantina({
  variable: "--font-karantina",
  weight: ["300", "400", "700"],
  style: ["normal"],
  display: "swap",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${helveticaNeue.variable} ${inter.variable} ${karantina.variable} antialiased`}
      >
        <ApolloClientProvider>
          <Header />
          {children}
          <Footer />
        </ApolloClientProvider>
      </body>
    </html>
  );
}
